version: '3'
services:
  react:
    container_name: react-production
    image: react-production:prod
    build:
      context: ./reactApp
      target: production  # Asegúrate de tener esta etapa 'production' en tu Dockerfile
      args:
        - NODE_ENV=production
      dockerfile: Dockerfile.prod  # Asegúrate de tener un Dockerfile.prod en ./reactApp
    ports:
      - "80:80"
    depends_on:
      - django

  django:
    image: django_app
    container_name: django_app
    build:
      context: ./djangoApp
    ports:
      - "8000:8000"
    volumes:
      - ./djangoApp:/app
    command: ["./wait-for-it.sh", "-t", "30", "mysql:3306", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    depends_on:
      - mysql

  node:
    container_name: node_app
    image: node_app
    build:
      context: ./node
    volumes:
      - ./node:/app
    ports:
      - "3000:3000"
    depends_on:
      - django
    command: ["node", "NodeMailer2.js"]

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=django-react
    volumes:
      - django_react_data:/var/lib/mysql
      - ./dumps:/docker-entrypoint-initdb.d:ro

volumes:
  django_react_data:
