# Generated by Django 5.1.1 on 2024-09-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_toys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toys',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
