# Generated by Django 5.1.1 on 2024-09-26 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_toys_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donaciones',
            fields=[
                ('donaciones_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_donante', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_donacion', models.CharField(blank=True, choices=[('monetaria', 'Monetaria'), ('alimento', 'Alimento')], max_length=50, null=True)),
                ('monto_donacion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad_donada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_donacion', models.DateField(blank=True, null=True)),
                ('descripcion_donacion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hist_ingredientes',
            fields=[
                ('hist_p_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('ingredientes_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recetas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cantidad_uso', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Toys',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='id',
            new_name='users_id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='age',
        ),
        migrations.AddField(
            model_name='users',
            name='rol',
            field=models.CharField(blank=True, choices=[('admin', 'Administrador'), ('cook', 'Cocinero'), ('vol', 'Voluntario')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='mail',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hist_ingredientes',
            name='users_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users'),
        ),
        migrations.AddField(
            model_name='donaciones',
            name='ingrediente_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ingredientes'),
        ),
        migrations.AddField(
            model_name='compras',
            name='proveedor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.proveedores'),
        ),
    ]
