# Generated by Django 5.1.1 on 2024-10-01 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_compras_donaciones_hist_ingredientes_ingredientes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('estudiante_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('grado', models.CharField(blank=True, max_length=50, null=True)),
                ('tiene_beca', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='donaciones',
            name='ingrediente_id',
        ),
        migrations.RenameField(
            model_name='recetas',
            old_name='id',
            new_name='receta_id',
        ),
        migrations.RemoveField(
            model_name='ingredientes',
            name='fecha_compra',
        ),
        migrations.RemoveField(
            model_name='recetas',
            name='cantidad_uso',
        ),
        migrations.CreateModel(
            name='Asistencias',
            fields=[
                ('asistencia_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asistencia', models.DateField(auto_now_add=True)),
                ('estudiante_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estudiantes')),
            ],
        ),
        migrations.CreateModel(
            name='RecetaIngredientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_uso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ingredientes')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.recetas')),
            ],
        ),
        migrations.AddField(
            model_name='recetas',
            name='ingredientes',
            field=models.ManyToManyField(through='api.RecetaIngredientes', to='api.ingredientes'),
        ),
        migrations.DeleteModel(
            name='Compras',
        ),
        migrations.DeleteModel(
            name='Proveedores',
        ),
        migrations.DeleteModel(
            name='Donaciones',
        ),
    ]
