# Generated by Django 5.1.1 on 2024-10-02 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_estudiantes_remove_donaciones_ingrediente_id_and_more'),
        ('api', '0009_alter_students_cedula'),
    ]

    operations = [
    ]
