# Generated by Django 5.1.1 on 2024-10-11 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_hist_pagos_fecha_pago_prueba'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiantes',
            old_name='estudiante_id',
            new_name='id_estudiante',
        ),
        migrations.RenameField(
            model_name='hist_pagos',
            old_name='estudiante_id',
            new_name='id_estudiante',
        ),
    ]
