# Generated by Django 5.1.1 on 2024-10-11 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_estudiante_id_estudiantes_id_estudiante_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiantes',
            old_name='id_estudiante',
            new_name='estudiante_id',
        ),
        migrations.RenameField(
            model_name='hist_pagos',
            old_name='id_estudiante',
            new_name='estudiante_id',
        ),
    ]
