# Generated by Django 5.1.1 on 2024-10-14 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_id_estudiante_estudiantes_estudiante_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hist_pagos',
            name='estudiante_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='api.estudiantes'),
        ),
    ]
