# Generated by Django 5.1.1 on 2024-10-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_delete_asistencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantes',
            name='almuerzo',
            field=models.BooleanField(default=False),
        ),
    ]
