# Generated by Django 5.1.1 on 2024-10-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_estudiante_id_estudiantes_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='rol',
            field=models.CharField(choices=[('estu', 'Estudiante'), ('prof', 'Profesor')], default='estu', max_length=5, null=True),
        ),
    ]
