# Generated by Django 5.1.1 on 2024-10-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_estudiantes_cedula_alter_estudiantes_seccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='rol',
            field=models.CharField(choices=[('Estudiantes', 'Estudiantes'), ('Profesor', 'Profesor')], default='estu', max_length=50, null=True),
        ),
    ]
