# Generated by Django 5.1.1 on 2024-11-03 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_hist_hechos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hist_hechos',
            name='pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hechos', to='api.estudiantes'),
        ),
    ]
