# Generated by Django 5.1.1 on 2024-11-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_hist_hechos_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='hist_ingredientes',
            name='reporte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Hist_hechos',
        ),
    ]
