# Generated by Django 5.1.1 on 2024-11-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_hist_ingredientes_reporte_delete_hist_hechos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hist_ingredientes',
            name='reporte',
        ),
        migrations.AddField(
            model_name='hist_pagos',
            name='hora',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='hist_pagos',
            name='reporte',
            field=models.TextField(blank=True, null=True),
        ),
    ]
