# Generated by Django 5.1.1 on 2024-11-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_hist_ingredientes_reporte_hist_pagos_hora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hist_pagos',
            name='fecha_desactivado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hist_pagos',
            name='hora',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
